export const solutionPillars = [
  {
    id: "pos",
    icon: "Receipt",
    title: "POS Billing",
    benefit: "Create invoices in seconds. • Print on the spot. • Route sales sync to head office.",
    anchor: "#feature-pos",
  },
  {
    id: "inventory",
    icon: "Package",
    title: "Inventory Management",
    benefit: "Track stock automatically. • Low-stock alerts. • Purchase tracking and movement history.",
    anchor: "#feature-inventory",
  },
  {
    id: "supplier",
    icon: "Truck",
    title: "Supplier Management",
    benefit: "Track purchases and supplier credit. • Credit and payment history. • One ledger per supplier.",
    anchor: "#feature-supplier",
  },
  {
    id: "credit",
    icon: "ShieldCheck",
    title: "Customer Ledger",
    benefit: "Outstanding invoices and payment history. • Ageing 0–30, 30–60, 60–90+ days. • Export for banks and auditors.",
    anchor: "#feature-credit",
  },
  {
    id: "routes",
    icon: "MapPin",
    title: "Route Sales System",
    benefit: "Branch, route, and staff under control. • Route P&L per period. • Visit and collection tracking.",
    anchor: "#feature-routes",
  },
  {
    id: "reports",
    icon: "BarChart2",
    title: "Reports & Profit",
    benefit: "Sales report, profit view, outstanding payments. • By period, branch, or route.",
    anchor: "#feature-reports",
  },
  {
    id: "vat",
    icon: "FileText",
    title: "VAT Compliance (UAE)",
    benefit: "VAT return and tax report ready. • Auto 5% per line. • FTA-compliant invoices.",
    anchor: "#feature-vat",
  },
  {
    id: "invoice",
    icon: "Mail",
    title: "Invoice PDF & Email",
    benefit: "Print professional PDF. • Email or WhatsApp in one click. • Your logo and TRN on every invoice.",
    anchor: "#feature-invoice",
  },
];
